### PR TITLE
Laminas continuous integration

### PR DESCRIPTION
**Pull request by basz**
attempt at using laminas/workflow-continuous-integration github action

please shoot

### CODE REVIEW

**Comment by basz** [comment]
it’s is based on https://github.com/prooph/standard-projections/pull/15 which should be merged first...

**Comment by basz** [comment]
Well that seems to run fine: https://github.com/basz/standard-projections/actions/runs/2992666797

with a bit of tweaking, for which I've made some PR to the actions

https://github.com/laminas/laminas-ci-matrix-action/pull/127
https://github.com/laminas/laminas-continuous-integration-action/pull/127

**Comment by basz** [comment]
please review (and #15)

**Comment by prolic** [comment]
Build passes on github actions, thanks @basz

**Pull request merged**
