### PR TITLE
allow php82

### PR DESCRIPTION
**Pull request by basz**
phpspec/prophecy supports php82 now

### CODE REVIEW

**Comment by basz** [comment]
ping

**Comment by zluiten** [comment]
ping @prolic @codeliner :)

**Comment by prolic** [comment]
Thank you

**Comment by basz** [comment]
able to do a release?

**Comment by prolic** [comment]
You're the boss 😂

**Comment by basz** [comment]
no boss in sight here... 😋

**Comment by basz** [comment]
Hey, you! Have the honour of being the last package (out of 270) before we go 8.2...

```
composer why-not php 8.2           
prooph/standard-projections v1.3.0 requires php (^7.4 || ^8.0, <8.2) 
```

**Comment by basz** [comment]
ping @prolic @codeliner

**Comment by prolic** [comment]
sorry for the delay: https://github.com/prooph/standard-projections/releases/tag/v1.4.0

**Comment by basz** [comment]
No sweat. Thank you!

**Pull request merged**
